### ISSUE TITLE
Package up CCA (Win and Mac) as GitHub releases?

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-Win#10]
Now that both aViewer http://www.paciellogroup.com/resources/aviewer/ and WAT http://www.paciellogroup.com/resources/wat/ are simply pointing to GitHub releases, can we explore what's involved in doing the same for CCA? I guess the first hurdle is that CCA (Win) and CCA (Mac) are completely separate. Can we move/fork CCA (Mac) to the TPG group perhaps, and do two separate releases (so there'd be a Mac and a Win button on http://www.paciellogroup.com/resources/contrastanalyser/ like now, but pointing to the two separate releases? /cc @ferllings @stevefaulkner @matatk @jun325

**Comment by matatk** [comment]
What we really need is to be able to build and release all of these from source ([as I mentioned before](https://github.com/ThePacielloGroup/aviewer/issues/3#issuecomment-127515454)), such that the WAT repo would use Git submodules to refer to the latest known-good revision of aViewer and CCA (though in theory anything on `master` should be good).

However this will require that we all have an IDE that works for us -- the one Steve found (linked from the post linked above) -- but we need to get it up-and-running and make it part of the build process.

In the meantime I could try doing [the same thing as for aViewer](https://github.com/ThePacielloGroup/aviewer/issues/5) (and now that's done, we could manually copy and paste it into the WAT repo and make an updated WAT release) -- but all of that takes time, and we really should be spending the time on making the build system work properly in future (IMHO) :-).

**Comment by patrickhlauke** [comment]
Pending the full works, I'd like to still see CCA Win (latest version from Jun, which fixed high-dpi work) and Mac being made available as a release here on github, so I can remove the links on https://www.paciellogroup.com/resources/contrastanalyser/ to files.paciellogroup.com

**Comment by patrickhlauke** [comment]
bumping this again @matatk @ferllings - thoughts on how best to get the CCA (Mac) version either on here, or as a separate repo under ThePacielloGroup? should we just fork yours, cedric? or is there some way to merge it into this as a single repo?

also ... how difficult would it be to do a manual release (same as for aViewer) of the Win and Mac versions, so i can update our site and send folks to a reasonably recent version of the tools?

**Comment by matatk** [comment]
We _could_ have both Win and Mac under the same repo, but the codebase is totally different, so probably best not.

I'm a bit confused as to where we are wrt where the latest code is -- if `master` in this repo is known-good then I can manually do a release.  We are still working on getting the means to remove all binaries from GH (except as part of releases).

If this one is ahead of WAT then I should do a new WAT release too.

**Comment by ferllings** [comment]
For the Mac, you can link to this page https://github.com/ferllings/Color-Contrast-Analyser-OSX/releases
(Note that there is no El Capitan version ATM.)

I don't see the point of have both version in the same repo: both tools don't share anything, and don't even have the same features.

What do you mean by "...to do a manual release..."

**Comment by patrickhlauke** [comment]
> What do you mean by "...to do a manual release..."

matt wants to set this whole repo up properly so that it only contains the sources, and through a build process creates the binary for the release (rather than having the binary as part of the repo itself, meaning that somebody has to compile it and then add it here).

**Comment by ferllings** [comment]
Ah ok, that's what I already did with CCA OSX

**Comment by patrickhlauke** [comment]
changed the link to the OS X version on https://www.paciellogroup.com/resources/contrastanalyser/ to point to https://github.com/ferllings/Color-Contrast-Analyser-OSX/releases/latest ... wasn't even aware you were already doing releases :)
