### ISSUE TITLE
Colour picker only works on main screen in multi-monitor setups

### ISSUE THREAD

**Issue by EricDunsworth** [ThePacielloGroup/CCA-Win#11]
It doesn't look like this has previously been brought up, so here it goes...

In v2.2a, in multi-monitor setups, the colour picker doesn't work properly on secondary screens. If I hover the picker overlay to my second screen, it gets "stuck" to the last state it was in on the main screen.

Any chance this could be looked into? Support would also be necessary for scenarios where each screen in a multi-monitor setup uses different resolutions.

**Screencap (main screen on the right and secondary on the left):**
![cca_2-monitors_screencap](https://cloud.githubusercontent.com/assets/1907279/9468428/9501c33c-4b0f-11e5-9806-8822eedf69de.png)

**Comment by matatk** [comment]
Thanks for reporting this. I am not sure if we actually have a multi-monitor setup to test this on, but it does seem to be a bug to me, so I will flag it as such, and we'll get to it as soon as we are able.

Did it work in any prior versions, do you know?

**Comment by EricDunsworth** [comment]
@matatk When I first started using it a few years ago, I think v2.2a was still the latest version at the time. Haven't tried any older versions.

Is there an archive of older releases out there somewhere?

**Comment by ghost** [comment]
Please try this version.
https://github.com/jun325/CCA/tree/develop/32bit

**Comment by EricDunsworth** [comment]
@jun325 Thanks :)! That version works way better. It also works fine with different resolutions across each screen.

The only (very) minor issue I noticed was that if I hover the colour picker overlay to the far edge of a screen that "connects" to another screen, the overlay doesn't show what's on the edge of the other screen unless my mouse cursor enters its viewport.

It's kind of difficult to explain, so here's a few screenshots of what I mean...

Cursor at far right edge of left screen (overlay's right side is "stuck" at a solid colour instead of showing the right screen's left edge):
![cca_test2_shot1](https://cloud.githubusercontent.com/assets/1907279/9549730/8f37a378-4d75-11e5-8aa1-786f40bab9ca.jpg)

Cursor moved to far left edge of right screen (both sides of the overlay are now ok):
![cca_test2_shot2](https://cloud.githubusercontent.com/assets/1907279/9549749/a9ad3ace-4d75-11e5-91b6-377625ab2652.jpg)

**Comment by matatk** [comment]
Thanks @jun325 :-). Is the source code for the new binary release in the `develop` branch, too?  If so, and if you're happy with it, we should merge this back to `master`.

**Comment by patrickhlauke** [comment]
I think there's no way around the minor issue concerning the edge/seam between the screens, as this comes down to how Windows exposes/breaks up the single desktop over multiple screens as discrete, separate viewports. But as the main problem seems to have now been addressed in #14 (which we'll release soon), I'm closing this :)
