### ISSUE TITLE
New release (High-DPI, multi-monitor support)?

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-Win#14]
A while ago @jun325 worked on some initial fixes for high-dpi displays https://github.com/jun325/CCA/commit/665286632c2d6b1733039f83ee83c8e4e2adca42

Is there any chance these changes can be promoted to master and a new public release be made?

**Comment by patrickhlauke** [comment]
seems the version in develop branch also solves multi-monitor issues as reported in #11 - so would definitely be a good thing to merge changes into master and make a new public release

**Comment by patrickhlauke** [comment]
nudge...anybody?

**Comment by matatk** [comment]
Sorry for the delay on this @jun325, @patrickhlauke.  I only see one changed file in https://github.com/jun325/CCA/commit/665286632c2d6b1733039f83ee83c8e4e2adca42 (the .exe), but some of the source code must have changed too, to make this fix happen?  Also there are a number of commits in Jun's develop branch _after_ that point; do we want to merge those in too?

I could just put the .exe from Jun's commit into master here, but we should ensure that the source code in master here is up-to-date, too.

**Comment by ghost** [comment]
I apologize for the delay in replying.
I uploaded latest CCA(binary and source files) yesterday. https://github.com/ThePacielloGroup/CCA-Win/commit/0c50a175216f1cce7463de5b7afdb26eaedaf07d
Could you try the high DPI support function?

**Comment by patrickhlauke** [comment]
Looks good - tested on Surface 3, color picker and Image > Screen overlay window all work correctly. This also fixes the eyedropper issue from #8 

Only tiny visual problem (possibly just related to Surface 3's specific pixel density, which I think is fractional 1.5) is the "Show contrast results..." checkbox which is missing the top border (likely falls in between pixels on the Surface) and the slightly cramped look compared to the low-res layout (like the padding on items seems a bit smaller, in proportion, to the actual controls/text)

> ![capture-lores](https://cloud.githubusercontent.com/assets/895831/15209338/6ab54c98-1828-11e6-8177-486d778e8e55.PNG)
> 
> <img width="960" alt="capture-hires" src="https://cloud.githubusercontent.com/assets/895831/15209350/78472dea-1828-11e6-8d42-7b2e1259f487.PNG">

**Comment by patrickhlauke** [comment]
(sorry, accidentally closed this instead of just commenting...doh)

**Comment by ghost** [comment]
please try this https://github.com/ThePacielloGroup/CCA-Win/commit/96984bb6723b82a4f6842135efee157544265d55

**Comment by patrickhlauke** [comment]
tried the 64bit version. the missing top border on the checkbox is fixed, but the overall padding/spacing of some elements till feels a tiny bit cramped. not a massive problem, but would be good to address it if it's not too much trouble

<img width="204" alt="capture" src="https://cloud.githubusercontent.com/assets/895831/15283416/3784b008-1b42-11e6-85fb-cafcc288844d.PNG">
