### ISSUE TITLE
Contrast Ratio Rounding Difference Between WAT CCA and Windows CCA

### ISSUE THREAD

**Issue by jgauvreau** [ThePacielloGroup/CCA-Win#15]
My team noticed slightly different color contrast calculations depending upon if they were using the Colour Contrast Analyser (CCA) launched from the Web Accessibility Toolbar (WAT > Colour > Contrast Analyser [application] option) versus downloading and installing the standalone Windows version of CCA.

For example if you enter the following HEX color codes Foreground:#444444  Background:#AFAFBB:
- The Windows stand alone version of the CCA calculates and displayed a Contrast ratio of 4.49:1
- The WAT version of the CCA calculates and displays a Contrast ratio of 4.5:1

Can the CCA Windows stand alone version be updated to round the result to one decimal place to be consistent with the results other developers/tester might see using the WAT version of CCA?

**Comment by patrickhlauke** [comment]
Confirmed. I seem to remember at some point this difference was introduced (either in the WAT or standalone version).

**Comment by patrickhlauke** [comment]
The latest version of CCA standalone in #14 (which we'll release properly soon) addresses this now.

> ![capture](https://cloud.githubusercontent.com/assets/895831/15209537/7a9efd06-1829-11e6-9adb-039efd1a9d78.PNG)
