### ISSUE TITLE
Windows 10: When having CCA in C:/Windows/Programs, on exit, error is shown

### ISSUE THREAD

**Issue by andreasbossard** [ThePacielloGroup/CCA-Win#16]
How to reproduce: 
1. Copy the 3 CCA-Files to C:\Windows\Program Files\ColourContrastAnalyser or C:\Windows\Program Files (x86)\ColourContrastAnalyser (I have the german version of Windows, so my instead of "Programs" I have "Programme", but I don't know if this can be a cause to the problem.)
2. Open Colour_Contrast_Analyser.exe
3. click the "x" on the upper right side to exit the application

This error message is shown:
![cca-error-message-onexit](https://cloud.githubusercontent.com/assets/502464/15398144/cf09419e-1de2-11e6-8eb2-c7ccf87562c4.png)

How to workaround: Copy the files to C:\ColourContrastAnalyser and it works.

**Comment by ghost** [comment]
Could you try the new version?
https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.3.0.6

**Comment by patrickhlauke** [comment]
Can't reproduce using latest version on Windows 10

**Comment by andreasbossard** [comment]
Me Too. Can't reproduce. Thank you for the new version @jun325 !
