### ISSUE TITLE
Add Value slider in addition to RGB sliders

### ISSUE THREAD

**Issue by mdmcginn** [ThePacielloGroup/CCA-Win#18]
With http://snook.ca/technical/colour_contrast/colour.htm, I use the Value slider almost exclusively, rather than the  RGB color sliders. I can get away with telling my designer, "I made the foreground color lighter. Does it look okay?" but I'm not sure I can get away with "I changed the RGB values of the foreground color and it no longer matches our brand color palette."

**Comment by ZoeBijl** [comment]
+1

**Comment by ghost** [comment]
I have already started developing HSV sliders functions. Could you wait about two weeks , please?

**Comment by ghost** [comment]
I have uploaded the new(beta version) CCA. Please try it. https://github.com/ThePacielloGroup/CCA-Win/commit/591761a9b471489caf6cf7cb2505420a6d106c53

**Comment by patrickhlauke** [comment]
Nice initial support for HSV @jun325. Tiny bug I found:
- select a color from the color select dropdown
- change one of the HSV values - the RGB sliders also update
- re-select the same color from the color select dropdown
- notice that the RGB sliders went back to their correct values, but the HSV sliders don't update to reflect the reset color

> ![cca](https://cloud.githubusercontent.com/assets/895831/17076703/e1d35408-50b0-11e6-8600-98f351392df8.gif)

**Comment by patrickhlauke** [comment]
additionally, wondering if it would be possible to:
- show the HEX text field next to color select/eye dropper (as in current CCA), but no need to also offer a separate "Display color values" switch in the "Options" menu
- make a menu with submenus under options for "Show sliders", with submenu options "RGB" and "HSV" (that act as checkboxes, so you can activate one, or the other, or both)

**Comment by matatk** [comment]
@jun325 the HSV support you've added looks great; thanks!

**Comment by ghost** [comment]
updated(bug fix and UI change) https://github.com/ThePacielloGroup/CCA-Win/commit/293bd4c91ab90562e24559701ca22e41ef501e98

**Comment by patrickhlauke** [comment]
looking good @jun325 ... feel free to merge it to master and we'll get a new release out with this

**Comment by patrickhlauke** [comment]
Closing, as this will go live once next release is out
