### ISSUE TITLE
Image file convert: "Nromal" instead of "Normal"

### ISSUE THREAD

**Issue by andreasbossard** [ThePacielloGroup/CCA-Win#19]
Tested with https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.3.0.6

In "Select image file" in the dropdown is written "Nromal". (English version)

I guess this is hardcoded because:
- I could not find "Nromal" in the en-language-ini
- "Normal" is written correctly in in "Select Window"

![cca-image-file-convert-nromal](https://cloud.githubusercontent.com/assets/502464/15822796/3ada1b6e-2bf8-11e6-827f-eb270e330028.jpg)

**Comment by ghost** [comment]
Please rename "Colour_Contrast_Analyser.ini" to "Default.ini". And put the file  in the "lang" folder.

**Comment by patrickhlauke** [comment]
Ah, my fault for packaging it that way (though wondering where the "Nromal" text came from is in that case)

**Comment by patrickhlauke** [comment]
Repackaged the zip to have the Default.ini file in the lang folder. https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.3.0.6

**Comment by patrickhlauke** [comment]
Closing this, as it's fixed in the upcoming release (and already fixed if using the language files in the correct location, as in our current new packaged format.
