### ISSUE TITLE
Package CCA as an installer

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/CCA-Win#2]
I have uploaded a folder with subfolders containing the various translations, would be good to create an install for CCA that allows user to choose their language

**Comment by patrickhlauke** [comment]
How easy/difficult would it be to create an actual installer (rather than distributing this as a zip file) ? @jun325 @matatk

**Comment by matatk** [comment]
I could make something with Inno Setup, probably would take a few hours to do it and test it -- but really I'm not convinced it's necessary; it doesn't really need installing.  If it were installed, would we just stick with having another copy of it inside WAT?

**Comment by patrickhlauke** [comment]
It could do with a proper installer, rather than having to make a folder somewhere, unzip the zip package, create your own shortcut to the program manually, etc.

**Comment by patrickhlauke** [comment]
And as WAT will be sunsetted in the not too distant future, I don't think this should be much of a blocker in making CCA nicer to install ;)

**Comment by matatk** [comment]
Good point; well made :-)  [ I guess the cat's out of the bag now... ]

Re installer: Inno Setup is something I can do (as above).  Need to get some time allocated for it (as it's probably not something I can just squeeze in, as it'll need a bit of testing).  Also can I assume that master here is the latest, up-to-date-with-fixes branch?

**Comment by patrickhlauke** [comment]
I'd hold off until #14 lands (if @jun325 gets around to looking at the padding/cut-off border on checkbox issue assuming it's non-trivial)...but for testing, try and use the develop branch

**Comment by patrickhlauke** [comment]
As language selection is easy (once the language folder is in the proper place, as is now the case in the new `package` folder https://github.com/ThePacielloGroup/CCA-Win/tree/master/package) when the app is running, I'd like to simplify this to just making the package an actual installer, rather than a `zip` file. Thoughts? Easy to do?

**Comment by ghost** [comment]
I uploded a example iss file https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/CCA.iss

**Comment by patrickhlauke** [comment]
@jun325 only just looked at this now. excellent stuff! i've tweaked the .iss file a bit, but beyond that it works nicely. for the next release (2.4) we should distribute the installer rather than the .zip :)

**Comment by patrickhlauke** [comment]
Closing this, as it will be resolved once the develop branch is merged to master and new release is pushed out

**Comment by ghost** [comment]
I fixed a small bug for the installer.
Could you rebuild the installer?

**Comment by patrickhlauke** [comment]
@jun325 merged `develop` back into `master` and created new release https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.4.0.9

Btw, for consistency: I'm using the "File version" number from the compiled executables as reference for the versioning here, but I see the "Product version" is 1.0.0.0. I guess we should standardize this somehow (ideally, product version being the same one as file version?). Same goes for the aViewer repo/executables/versions (though there I'm going by the "Product version", as the 32 and 64 bit versions had differing "File version"...

![cca-file-props](https://cloud.githubusercontent.com/assets/895831/18253104/06103a42-738a-11e6-8012-ff9e17e4fc9d.PNG)
