### ISSUE TITLE
Redundant/duplicate/broken ini files? (was UTF-8 issues with ini files?)

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-Win#20]
The Czech.ini, French.ini, German.ini, Italian.ini, Spanish.ini files seem to have an encoding issue with certain characters (at least when opening these in a text editor).

**Comment by patrickhlauke** [comment]
![capture1](https://cloud.githubusercontent.com/assets/895831/15827688/0fd867c0-2c04-11e6-9c3f-dd8841ffc03f.PNG)

**Comment by patrickhlauke** [comment]
specifically, it's the ini files in the https://github.com/ThePacielloGroup/CCA-Win/tree/master/32bit/lang folder. Is this folder redundant? Is this just a duplicate (but broken, possibly due to wrong text file encoding) of https://github.com/ThePacielloGroup/CCA-Win/tree/master/languages ? Which ones are the correct ini files, and what's the preferred way to package these up for a release?

**Comment by patrickhlauke** [comment]
In short: could we clean up the repo and make it clear what needs to be packaged, and how, for zipping up and release?

**Comment by stevefaulkner** [comment]
Hi @jun325 could you respond to this issue - thanks!

**Comment by ghost** [comment]
@stevefaulkner Do you still have the UTF-16 edition of ini files? You were managing those files.

the https://github.com/ThePacielloGroup/CCA-Win/tree/master/languages is unnecessary folder.
I don't understand the usage of this folder because I'm not making this folder.

**Comment by patrickhlauke** [comment]
@jun325 just wondering: how can a user switch languages? do they manually need to replace `Colour_Contrast_Analyser.ini` in the folder where they keep the `.exe` file (i.e. they grab the relevant language, like `German.ini` and rename it to `Colour_Contrast_Analyser.ini` ?

**Comment by patrickhlauke** [comment]
And for packaging up CCA for download, what's the most sensible folder structure ? would it make sense to make the package more like:
- root folder of the zip
  - Colour_Contrast_Analyser32bit.exe
  - Colour_Contrast_Analyser64bit.exe
  - Colour_Contrast_Analyser.ini (the default one)
  - Colour_Contrast_Analyser.ico (is this needed at all, or is the icon already embedded into the exe?)
  - languages folder (containing the various translated ini files)

(I suppose this would then also be relevant for when/if we get an actual installer, per https://github.com/ThePacielloGroup/CCA-Win/issues/2 )

**Comment by ghost** [comment]
The CCA has the language switch menu.
![cca](https://cloud.githubusercontent.com/assets/5038132/16481228/12586768-3ee5-11e6-9aaf-9b174a205aea.jpg)

folder structure:
- root folder of the zip
  - Colour_Contrast_Analyser32bit.exe
  - Colour_Contrast_Analyser64bit.exe
  - Colour_Contrast_Analyser32bit.ico
  - Colour_Contrast_Analyser64bit.ico
  - "lang" folder (containing the various translated ini files)

The icon file is used by HTML in the "about" dialog.

**Comment by patrickhlauke** [comment]
Super, that's very helpful. I may reorganise the repo a bit...perhaps set up a "dist" folder where we have that structure, so that it can be easily zipped up in future
