### ISSUE TITLE
Title bar changes to "0"

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-Win#23]
In the latest executable on `develop`, after choosing a colour from the windows color picker dropdown, the title bar (normally "Colour Contrast Analyser") changes to "0"

![cca](https://cloud.githubusercontent.com/assets/895831/18167848/a37b915c-704a-11e6-839c-9d2a58d6b47f.gif)

/cc @jun325

**Comment by ghost** [comment]
I fixed it. https://github.com/ThePacielloGroup/CCA-Win/commit/80044f29ad5ee42c1171e62dbe5cf4307dfea8bc

**Comment by patrickhlauke** [comment]
Thanks @jun325 ... confirming that it's fixed. I'll roll out our first installer release in a bit.
