### ISSUE TITLE
UI has some "issues" with desktop zoom

### ISSUE THREAD

**Issue by MartinL0815** [ThePacielloGroup/CCA-Win#25]
Hi,

I'm of those working with high-contrast-mode and desktop zoom (150%).

The desktop zoom causes problems in the position of controls, so that partly the displayed text gets truncated vertically at its bottom:
1. ![Screenshot 1](https://cloud.githubusercontent.com/assets/525700/19189013/f232df82-8c95-11e6-8835-21e2047307ac.png)
2. ![Screenshot 2](https://cloud.githubusercontent.com/assets/525700/19189039/09a9f9fc-8c96-11e6-8281-ec881171ead3.png)

I'm not using a monitor with a higher resolution, so others might use a higher desktop zoom and might have more UI issues.

Thanks!

Martin

**Comment by patrickhlauke** [comment]
I'll take a guess that the vertical size of the UI elements is set in a fixed metric, rather than being based on the font size.

**Comment by MartinL0815** [comment]
Yes, it looks like.

Using so called Dialog Units - the standard dialog template unit to position and size controls in Win32 - would bring the font size into account.

If it is about using a kind of CSS to style the controls, than the unit "em" would be my choice.

**Comment by ghost** [comment]
I changed the resize function. Could you try this?https://github.com/ThePacielloGroup/CCA-Win/commit/b8445bedc4f310fb12535a06553efbc5ad1d5825

**Comment by MartinL0815** [comment]
You mean reviewing your pascal code? Or trying a preview/prerelease executable?

**Comment by stevefaulkner** [comment]
On 7 November 2016 at 15:37, Martin Lemburg notifications@github.com
wrote:

> Or trying a preview/prerelease executable?

i think jun means this

## 

Regards

SteveF
Current Standards Work @W3C
http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/

**Comment by patrickhlauke** [comment]
Yes, trying the executables...

32bit https://github.com/ThePacielloGroup/CCA-Win/blob/b8445bedc4f310fb12535a06553efbc5ad1d5825/package/Colour_Contrast_Analyser32bit.exe

64bit https://github.com/ThePacielloGroup/CCA-Win/blob/b8445bedc4f310fb12535a06553efbc5ad1d5825/package/Colour_Contrast_Analyser64bit.exe

(just pop them on your Desktop or wherever, they don't need to be put in the same folder as the installed proper version)

**Comment by MartinL0815** [comment]
Ok - got it.

Downloaded 32bit build and started it right from the browser:
1. There was an error message about not finding "something". This error message contained Asian characters and was partyl unreadable.
2. The left column was not as wide and high as necessary, but after switching on/off the RGB/HSV sliders, the UI was scaled correctly.
3. Restarted the application from the explorer and got no error message, but a correctly scaled UI: 
![correctly scaled UI](https://cloud.githubusercontent.com/assets/525700/20064635/a470fa84-a50b-11e6-8d53-dd9041ff916c.png)
4. In comparison a previous release: 
![former wrongly scaled UI](https://cloud.githubusercontent.com/assets/525700/20064912/918972a6-a50c-11e6-9a68-d87679c6ddf5.png)

Since this page crashed in Chrome while writing a comment to this issue, the pasted and not saved screenshots are lost!
And sincerely starting the executable does not cause the initial problem, I'm not able to reproduce English/Asian error message!

**Comment by ghost** [comment]
> 1. There was an error message about not finding "something". This error message contained Asian characters and was partyl unreadable.

I fixed this(ini not found) error.
new 32bit  executable file: https://github.com/ThePacielloGroup/CCA-Win/blob/aab26b06c287b4d399fa63381f8980ddde1560d7/package/Colour_Contrast_Analyser32bit.exe

**Comment by patrickhlauke** [comment]
@MartinL0815 if you get a chance, could you try the most recent release and let us know if you're still experiencing problems? https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.4.0.23

**Comment by MartinL0815** [comment]
Thanks for pointing out the chance to test the new release.

The only point I have are the icons/bitmaps used to signal success and failure.
They could be in a different coloring (inverted?) on black based high-contrast.

But there seem to be no "problem" or issue.

Best regards,

Martin

**Comment by patrickhlauke** [comment]
Perfect, thank you for checking. I'll close this for now, as we'll likely revisit icons in a bigger overhaul soon
