### ISSUE TITLE
Screen Convert not working on Multi-Monitor Environment

### ISSUE THREAD

**Issue by OLLI-S** [ThePacielloGroup/CCA-Win#26]
I have two monitors on my Computer and work with CCA 2.4.
The Screen convert (Menu "Image -> Screen") shows an white Image of the selected area instead of the screened application.
This error always occurs, no matter if the target application is in the primary monitor (normally it is) or on the second monitor.
When I close CCA, deactivate the second monitor in Windows and start CCA again, the Screen convert is working normally.
**This way CCA is not usable for our team.**

**Comment by ghost** [comment]
I can't reproduce it yet. but I am investigating the cause.

**Comment by OLLI-S** [comment]
If you need any system specs or any data that might help, please tell me!
I will try to help you finding the bug.

**Comment by ghost** [comment]
Does the "color picker" function work well?

**Comment by OLLI-S** [comment]
The "Color Picker" works on both monitors.

**Comment by bethwhitmer** [comment]
I just wanted to confirm that I am having this exact same issue. When I am hooked up to my dual monitor setup the Screen Convert functionality doesn't work (just a white screen) but it does work when I'm disconnected.

**Comment by ghost** [comment]
I changed some functions. Could you try the latest version?
https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser32bit.exe

**Comment by bethwhitmer** [comment]
Good morning,

I downloaded the latest version and the issue is no longer happening. Thanks!

Beth Whitmer, CUA
Senior Consultant
Human Factors Practice
(703) 227-4166

**Comment by OLLI-S** [comment]
I dit not have CCA installed and just downloaded and executed the new EXE.
The Screen convert (Menu "Image -> Screen") is working much better, but here I have a **refresh problem**.

When I select to see "Grayscale" then the image in the windows "Screen convert" is displayed in grayscale (this is OK).
But when I then select "Protanopia" from the combo box then nothing changes (I still see grayscale).
When I now drag the "Screen convert" 1 pixel to the left, then the image is refreshed and everything is shown in "Protanopia".

Next I closed the "Screen convert" windows and opened it again.
Here I did not change anything abd although "Protanopia" is selected, the image in the "Screen convert" window is displayed normally (like you see it without color blindness).
When I now click on "Parallel view" then I see 6 white images.
When I close the "Parallel view" and drag the "Screen Convert" window some pixels (so I see the "Protanopia" view) and then open the "Parallel view" then I see 6 different images (as it should be).

**Comment by ghost** [comment]
I have uploaded new files.
32bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser32bit.exe
64bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser64bit.exe

**Comment by patrickhlauke** [comment]
@OLLI-S does the above exe still cause problems for you?

**Comment by OLLI-S** [comment]
@patrickhlauke No, unfortunately not

I have Windows 7 x64 and downloaded the 64 bit EXE you have provided.
I do not have any previous version of CCA installed.

I select "Image -> Screen" and move the CCA window to the proper position.
Then I select "Grayscale" -> Screen is displayed in Grayscale
Then I select "Protanopia" -> Screen is still displayed in Grayscale
When I move the CCA window with the mouse 1 pixel, it is refreshed and displayed correctly.

**Comment by OLLI-S** [comment]
How is the status on this issue?
Anything ready to be tested?

**Comment by ghost** [comment]
Did you try the latest version? https://github.com/ThePacielloGroup/CCA-Win/tree/develop/package
