### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by OLLI-S** [ThePacielloGroup/CCA-Win#27]
We are using an older Version of CCA because it can be used without an Installation.
In our company we are **not allowed** to install applications (you need administrator rights, normal users can not install anything, they have no rights).
Unfortunately Version 2.4 is only available as a setup package.
Please release also an portable version of CCA.

**Comment by patrickhlauke** [comment]
a portable version would simply be the contents (minus the .iss file) of the "package" folder https://github.com/ThePacielloGroup/CCA-Win/tree/master/package

For the next release we can explicitly wrap this up as a .zip and add it to the relevant release, in addition to the installer file itself.
