### ISSUE TITLE
Cataracts simulation: Difference too small

### ISSUE THREAD

**Issue by andreasbossard** [ThePacielloGroup/CCA-Win#29]
The cataracts-simulation is a great tool to make other people concscient how someonewith cataracts sees the screen. But unfortunately the difference is very small. Here an example of a cataracts simulation of http://edition.cnn.com/
![cca-cataracts-small-difference](https://cloud.githubusercontent.com/assets/502464/19432722/1d18d1b4-945e-11e6-8579-b4190cc65269.jpg)

In order to make this cataracts-simulation more effective, I would think it would be better to show the simulation more blurred. What do you think? (What was the decision for the currently selected blur-factor?)

**Comment by stevefaulkner** [comment]
yes i agree more blur would be good, @jun325 can you tweak this?

**Comment by ghost** [comment]
How is this blur effect? https://github.com/ThePacielloGroup/CCA-Win/commit/b8445bedc4f310fb12535a06553efbc5ad1d5825

**Comment by patrickhlauke** [comment]
![capture](https://cloud.githubusercontent.com/assets/895831/20043232/5e9d5af0-a481-11e6-8ac0-069268c7cbd6.PNG)

Looks good to me

**Comment by andreasbossard** [comment]
Much better. Thank you @jun325 !

**Comment by patrickhlauke** [comment]
Closing, as this will make it into the next release then :)
