### ISSUE TITLE
standalone Mac app consistently crashes

### ISSUE THREAD

**Issue by lbw8lrrh** [ThePacielloGroup/CCA-Win#3]
This is a great app but it crashes so often (every few times I try to change the color) that it is extremely frustrating and painful to use. I keep submitting crash reports but thought I'd open an issue. I'm running a MacBook Pro 15" running Yosemite.

**Comment by ferllings** [comment]
The OSX version has been fully rewrited for Yosemite.
https://github.com/ferllings/Color-Contrast-Analyser-OSX
You can give a try to the beta version: 
https://github.com/ferllings/Color-Contrast-Analyser-OSX/blob/master/Colour%20Contrast%20Analyser.app.zip?raw=true
