### ISSUE TITLE
Contrast ratio and rounding

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-Win#30]
Following discussion here https://github.com/w3c/wcag/issues/200#issuecomment-255457358 there is/will be an issue with the way in which CCA currently rounds results to single decimal point and then uses the rounded value for its pass/fail determination.

4.5:1 and 3:1 need to be treated as absolute thresholds, and the non-rounded result needs to be assessed against this contrast. so for instance 4.49124578:1 needs to fail as it is below 4.5:1 in absolute terms - it can't be rounded first to 4.5:1 and THEN compared to the threshold figure.

this may require some extra tweaking of the displayed text for these cases. Maybe for values that are between 4.45 - 4.4999999 (or whatever the precision internally is) the output should read "The contrast ratio is: just below 4.5:1" (and the same for 2.95 - 2.9999 for the 3:1 ratio)

xref https://github.com/ThePacielloGroup/CCA-OSX/issues/23

**Comment by DavidMacDonald** [comment]
Halloween bug 
https://twitter.com/stevefaulkner/status/791944961952407552
Mwha ha ha ha

**Comment by patrickhlauke** [comment]
:ghost: :ghost: :ghost:

**Comment by ghost** [comment]
updated https://github.com/ThePacielloGroup/CCA-Win/commit/b8445bedc4f310fb12535a06553efbc5ad1d5825

**Comment by patrickhlauke** [comment]
@jun325 tested out the new 64 bit exe. the rounding seems to work perfectly (using #777777 / #FFFFFF as a test combination fails and shows "just below 4.5:1")  (but see my comment about default.ini values having regressed?)

**Comment by ghost** [comment]
Sorry. It's my fault. I have just uploaded correct ini.

**Comment by MakotoUeki** [comment]
Have you fixed this issue with the latest version 2.4.0.10? It seems that it is still 4.5:1, not 4.48:1 when using #777777 / #FFFFFF with 2.4.0.10. I'm not sure if I uninstalled the previous version appropriately though.

One more thing. Please specify the version number (ex. "2.4.0.10", not "2.4") on the "About" panel (menu [Help] - [About ...]) so that users could confirm the version they are using and they could distinguish the bug-fixed version from the previous versions.

**Comment by patrickhlauke** [comment]
@jun325 did this regress? confirming that in the latest version, #777777/#FFFFFF still returns a pass / 4.5:1, rather than a fail "just below 4.5:1"

**Comment by patrickhlauke** [comment]
@jun325 ah, it actually seems you never pushed the fixed version to the stable branch here. are the changes to the rounding good to be added here? once this is done, i'll create a new release package

**Comment by patrickhlauke** [comment]
The latest release https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.4.0.23 includes the correct rounding, as well as showing the full version number in the "About" dialog.

**Comment by patrickhlauke** [comment]
> ![cca2 4 0 23](https://cloud.githubusercontent.com/assets/895831/23258075/8409239a-f9be-11e6-9840-c3d86afa7964.png)

**Comment by stevefaulkner** [comment]
> "this may require some extra tweaking of the displayed text for these cases. Maybe for values that are between 4.45 - 4.4999999 (or whatever the precision internally is) the output should read "The contrast ratio is: just below 4.5:1" (and the same for 2.95 - 2.9999 for the 3:1 ratio)" 

although the reporting of the non rounded result 4.45 - 4.4999999 is shown as a fail, the displayed value is still rounded without indication "The contrast ratio is: 3.0:1"  so needs to either report the actual result to 2 decimal places or add the clarification text "just below" /cc @jun325

**Comment by jake-abma** [comment]
Hi @patrickhlauke, any idea when a new Mac version will be launched? At the moment the two versions (Mac / Windows) have different results: https://developer.paciellogroup.com/resources/contrastanalyser/

Thx!

**Comment by patrickhlauke** [comment]
@stevefaulkner you sure you're on the latest version? it IS showing the "just below" bit in the result for me.

**Comment by patrickhlauke** [comment]
@jake-abma unfortunately no indication just yet when the Mac one will be updated, sorry. Will discuss with @stevefaulkner

**Comment by stevefaulkner** [comment]
> @stevefaulkner you sure you're on the latest version? it IS showing the "just below" bit in the result for me.

probably not then, will check and close bug if so.

> @jake-abma unfortunately no indication just yet when the Mac one will be updated, sorry. Will discuss with @stevefaulkner

Am organising @ferllings to have time to work on it
