### ISSUE TITLE
About dialog doesn't show current version

### ISSUE THREAD

**Issue by SetTrend** [ThePacielloGroup/CCA-Win#31]
I just downloaded version 2.4.0.9.

The About box, however, shows version 2.2a.

**Comment by patrickhlauke** [comment]
Can't seem to reproduce this when using the installer from https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.4.0.9

Just to check, did you have a previous version? Did you do a fresh install?

**Comment by patrickhlauke** [comment]
![capture](https://cloud.githubusercontent.com/assets/895831/22471018/06665090-e7c9-11e6-93b4-5b7cb5c68bb6.PNG)

**Comment by SetTrend** [comment]
#### I downloaded the installer from here:

![cca](https://cloud.githubusercontent.com/assets/9283914/22474447/18ad0f38-e7dc-11e6-929a-cba7c6488ecd.png)

It was a fresh installation on this machine.

#### The error actually is in the `German.ini` file:

![cca2](https://cloud.githubusercontent.com/assets/9283914/22474628/b370e4d6-e7dc-11e6-828a-344ef426936f.png)

Perhaps the version information should be taken from the actual program data. Then it wouldn't be necessary to update all the translations to accommodate for the new version.

**Comment by patrickhlauke** [comment]
Fixed (by manually changing all related .ini files) in https://github.com/ThePacielloGroup/CCA-Win/commit/dafb44595056900bde36db734d632d5a3349768c

New release: https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.4.0.10
