### ISSUE TITLE
Colour select menu - Occurs on every window if you don't close it

### ISSUE THREAD

**Issue by fredrikengseth** [ThePacielloGroup/CCA-Win#35]
Hi, I found a minor bug using CCA, thought you should be aware of it. When opening the color select menu, without selecting a color or closing it, the dropdown occurs when shifting windows. See the images below: 

For instance, opening the dropdown in the CCA in front of the browser.
![image](https://cloud.githubusercontent.com/assets/25005918/25267454/22ece554-2675-11e7-91d6-656efcda5d1d.png)

When opening another tab in the browser, the dropdown list occur in the next tab. This also happens if you open another programs. This is just one example.
![image](https://cloud.githubusercontent.com/assets/25005918/25267665/f594e43e-2675-11e7-8cae-6389030c909d.png)

**Comment by jun325** [comment]
I have just uploaded the new files. Could you try this version?
32 bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/master/package/Colour_Contrast_Analyser32bit.exe
64 bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/master/package/Colour_Contrast_Analyser64bit.exe

**Comment by ghost** [comment]
I have just uploaded the new files. Could you try this version?
32 bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser32bit.exe
64 bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser64bit.exe
