### ISSUE TITLE
When we install the software, it does not ask for to create a shortcut.

### ISSUE THREAD

**Issue by srinivasskc** [ThePacielloGroup/CCA-Win#36]
When we install the software, it does not ask for to create a shortcut. - Windows 10

**Comment by patrickhlauke** [comment]
adding this for reference http://www.jrsoftware.org/ishelp/index.php?topic=iconssection

**Comment by patrickhlauke** [comment]
Closed by https://github.com/ThePacielloGroup/CCA-Win/commit/cb945f611e96cc0471153fa4d49133727dfd3888 - this will take effect in the next release
