### ISSUE TITLE
Feature Request: Option to Sync RGB Track Bars

### ISSUE THREAD

**Issue by basiphobe** [ThePacielloGroup/CCA-Win#37]
It would be handy to have an option, probably a check box below the sliders so it can be toggled quickly, that would sync the RGB track bars at their current values. This would provide a convenient way to adjust all three values at once.

**Comment by ghost** [comment]
I added "Sync" check box.
new 32 bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser32bit.exe
new 64 bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser64bit.exe
![cca_ss](https://cloud.githubusercontent.com/assets/5038132/26751077/2957d23c-486c-11e7-99dd-059213fcd549.JPG)
