### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-Win#41]
Same as with aViewer https://github.com/ThePacielloGroup/aviewer/issues/32 I made a new app icon. @jun325 could you recompile the latest 32bit and 64bit versions using this, so we can get the next release with the most recent bugfixes etc ready?

**Comment by patrickhlauke** [comment]
For reference, here's the look of the icon at large sizes and a more abstract/stylised version at 16x16 pixels

![256x256](https://cloud.githubusercontent.com/assets/895831/26161531/185c951a-3b1c-11e7-9486-39854958a8d2.png)

![16x16](https://cloud.githubusercontent.com/assets/895831/26161538/1af3d6bc-3b1c-11e7-84a6-9709dcf0f615.png)

**Comment by ghost** [comment]
I have uploaded a new version(2.5.0). https://github.com/ThePacielloGroup/CCA-Win/commit/9e7964bfed8659a8bd14ddafb276a723c9050781

changes:
- app icon
- added "Sync" check box https://github.com/ThePacielloGroup/CCA-Win/issues/37
- Version/product numbering

**Comment by patrickhlauke** [comment]
Thanks for all your hard work there @jun325 !
