### ISSUE TITLE
Installer matched for "Malware.Heuristic!ET#81%"

### ISSUE THREAD

**Issue by TGBXX** [ThePacielloGroup/CCA-Win#42]
When scanned through VirusTotal, the CCA installer matches for a malware identified as "Malware.Heuristic!ET#81% (cloud:NENaB3GUWt)".

Results can be seen here: https://virustotal.com/en/file/39fb9436d0e2eea4e3d2a50e18417b223f028a5f13d120225e84b80db85a8f0e/analysis/1495679631/

Please advise if this is a false positive or a legitimate find.

**Comment by patrickhlauke** [comment]
This appears to be a false positive (based on the heuristics used by VirusTotal), as other tools (like Windows Defender running a local scan and Kaspersky's https://virusdesk.kaspersky.com/) don't flag the installer as an issue.
