### ISSUE TITLE
Spacing in results text

### ISSUE THREAD

**Issue by matatk** [ThePacielloGroup/CCA-Win#44]
I think the results would look clearer if there was a space between "Foreground:" and "Background:" and the "#" before the hex code.

**Comment by ghost** [comment]
I added space between them.
32bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser32bit.exe
64bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser64bit.exe

**Comment by matatk** [comment]
@jun325: looks good; thank you :-)
