### ISSUE TITLE
CCA 2.5.0.0 not working in Windows10 - Chinese lettering and error messages in Eng version

### ISSUE THREAD

**Issue by pfowles** [ThePacielloGroup/CCA-Win#48]
CCA has worked on/off but recently it keeps showing errors that file is not found on system then loading CCA . 
I then can't use CCA as it keeps showing issues like Chinese lettering in error boxes when using the picker, any other feature, or "(spurious chinese) The filename, directory name, or volume label syntax is incorrect" on exit. I can only close this using task manager.

**Comment by patrickhlauke** [comment]
just to be sure, is this using the proper installer version https://github.com/ThePacielloGroup/CCA-Win/releases ?

what version of Windows?

**Comment by pfowles** [comment]
Yes I got the installer through your main website, https://developer.paciellogroup.com/resources/contrastanalyser/ , which redirected to the page you mention (above) on GitHub.

Windows 10 is the operating system used

**Comment by patrickhlauke** [comment]
Can't replicate the issue. Perhaps if you could grab a screenshot of one of the chinese error boxes, that may provide us with a clue of what's going on.

**Comment by pfowles** [comment]
This is the error I get when I try and load up CCA - clicking ok loads CCA
<img width="251" alt="ccastart" src="https://user-images.githubusercontent.com/21061504/32050793-0a1d801a-ba4a-11e7-8004-c2a09b4fd379.PNG">

This is the error when I try and use the colour picker. The hex values and sliders appear to work fine
<img width="147" alt="ccapicker" src="https://user-images.githubusercontent.com/21061504/32050924-9260a150-ba4a-11e7-93a3-f196e04538c4.PNG">
 
The Screen Analyser
<img width="351" alt="ccasa" src="https://user-images.githubusercontent.com/21061504/32051125-5a1dc92a-ba4b-11e7-8b65-d990b9c945cf.PNG">


This is the error I keep getting whenever I try to close the application window, have to use Task Manager to close
<img width="360" alt="cca" src="https://user-images.githubusercontent.com/21061504/32050124-9e0714c4-ba47-11e7-819b-90aa4f4f425f.PNG">

**Comment by ghost** [comment]
I have just updated.
32bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser32bit.exe
64bit exe: https://github.com/ThePacielloGroup/CCA-Win/blob/develop/package/Colour_Contrast_Analyser64bit.exe
probably /My Documents/CCA.ini is unwritable(or can't be create) for some reason.
I hid the error dialog but settings will not be saved.

**Comment by pfowles** [comment]
So is there a fix in place?

**Comment by patrickhlauke** [comment]
did you try the above executables? do they still bring up the error? (i know these suppress notification, rather than address, but as the problem itself seems related to permissions/user accounts, it may be a while before the fundamental problem can be thoroughly addressed)

**Comment by pfowles** [comment]
It appears to work no error messages appear on the corrected version. Thanks
