### ISSUE TITLE
Convert/Simulate window - multiple modes

### ISSUE THREAD

**Issue by hvanhoose** [ThePacielloGroup/CCA-Win#5]
It would be useful when checking for different conditions to be able to see all those conditions in parallel, based on a given sample of the screen. Then I could see side by side (and side and side) comparisons between unaltered and simulated conditions.

**Comment by ghost** [comment]
I added "Parallel view" button. "Parallel view" window opens when the button is clicked.
Please refer to the following images.
![ss1](https://cloud.githubusercontent.com/assets/5038132/10932282/f2d764c2-8312-11e5-99e8-412861a052c4.jpg)
![ss2](https://cloud.githubusercontent.com/assets/5038132/10932288/f82351a2-8312-11e5-808b-afb2dab1d1cc.jpg)

**Comment by patrickhlauke** [comment]
Confirming that this works in #14 (which we'll release soon)
