### ISSUE TITLE
CCA exits with an error when dragging it from one screen to another and back

### ISSUE THREAD

**Issue by wilcovanesch** [ThePacielloGroup/CCA-Win#54]
**Environment**

Display 1: 1920x1080, 14", AsusPro laptop, Intel HD Graphics 620
Display 2: 1920x1080, 23", Dell monitor
Display 1 is the primary display, on which CCA loads initially.
CCA 2.5.0.0 on Windows 10.

**Steps**

1. Open CCA on the primary display.

<img width="337" alt="before dragging to other screen" src="https://user-images.githubusercontent.com/7155173/42884652-29bdeb96-8a9f-11e8-86ea-595eeb8625ac.PNG">

2. Drag CCA from the primary display to the secondary display

<img width="149" alt="after dragging to other screen" src="https://user-images.githubusercontent.com/7155173/42884664-2f234504-8a9f-11e8-9632-4b6b8494fa32.PNG">

*Note:* when CCA is instead loaded up from the secondary screen, it shows at roughly 4 times this size.

3. Drag CCA back from the secondary display to the primary display

<img width="158" alt="colour contrast analyser error on dragging across screens" src="https://user-images.githubusercontent.com/7155173/42884591-050db498-8a9f-11e8-872f-355ac1ac3430.PNG">

**Comment by ghost** [comment]
Could you try the latest version?
CCA 2.5.9: https://github.com/ThePacielloGroup/CCA-Win/tree/develop/package

**Comment by wilcovanesch** [comment]
Thank you, the issue is not present in the develop branch (update 2.5.9).
