### ISSUE TITLE
Interactive simulation

### ISSUE THREAD

**Issue by hvanhoose** [ThePacielloGroup/CCA-Win#6]
I would appreciate a way to put entire screens into simulation modes while allowing me to interact with everything on that screen (e.g., edit a document in deuteranopia vision). Color Oracle can simulate entire screens but also doesn't allow for interaction.

Also for flagging contrast ratio fails, interactively highlighting those in a simulation mode would save a lot of time when exploring different color variations.

**Comment by patrickhlauke** [comment]
As useful as this would be, I fear that because of the amount of recoding this would involve, it's not likely to happen in the foreseeable future. Closing this, but we may revisit the idea at a later date. Thanks.
