### ISSUE TITLE
Color picker on high-dpi displays is incorrect

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCA-Win#7]
When using a windows machine with a high-dpi display (for instance, a Surface 3, where the device pixel ratio is 1.5), the color picker goes out of sync with the display itself - the magnified area seems to follow what would be the 1.0 pixel ratio, meaning that the pixels that are magnified/picked are not those that are under the mouse cursor's position).

![untitled](https://cloud.githubusercontent.com/assets/895831/8218352/5402a712-153a-11e5-9ee2-55efc6c2311f.png)

**Comment by ghost** [comment]
I will fix it ASAP.

**Comment by patrickhlauke** [comment]
Closing this as https://github.com/jun325/CCA/commit/665286632c2d6b1733039f83ee83c8e4e2adca42 (mostly, despite some very minor spacing issue) addresses the problem.
