### ISSUE TITLE
Color picker stays as pointer arrow

### ISSUE THREAD

**Issue by jssh** [ThePacielloGroup/CCA-Win#8]
Previously when I used the color picker the "eye drop" changed to a square that changed size depending on the pixel options. Now, no matter what pixel size I choose the color selector is a regular size pointer arrow. This makes it much harder to select the part of text I want.
I am using v2.2a.

**Comment by patrickhlauke** [comment]
This is now fixed in the upcoming new version https://github.com/ThePacielloGroup/CCA-Win/issues/14
