### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by tuxayo** [ThePacielloGroup/CCA-Win#9]
As it works on Windows and OSX, is it completely platform independent or did that required a lot of specific code for each platform?

**Comment by ferllings** [comment]
Windows and OSX version do not share any code. Both have been developed specifically for the platform on which they run

**Comment by tuxayo** [comment]
Ok, thanks for the info. Good job making such an app also! :-)

**Comment by patrickhlauke** [comment]
Closing this, as there are no specific plans (nor resources) at the moment for a Linux version I'm afraid.
